# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param x0 initialization
#' @param y0 initialization
#' @param n default is 10
#' @param a default is 1
#' @param b default is 2
#' @return a random sample of size n
#' @examples
#' \dontrun{
#' N <- 5000
#' x0 <- 0.5*n
#' y0 <- (x0+a) / (n+a+b)
#' Chain_Cpp <- gibbsC(N, x0, y0)
#' }
#' @import microbenchmark
#' @importFrom Rcpp evalCpp
#' @importFrom stats rbinom rbeta
#' @useDynLib WAP
#' @export
gibbsC <- function(N, x0, y0, n = 10L, a = 1L, b = 2L) {
    .Call('_WAP_gibbsC', PACKAGE = 'WAP', N, x0, y0, n, a, b)
}

